# Generated by Django 4.2.5 on 2024-05-20 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("image", models.TextField()),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("feedback", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("placed", "Placed"),
                            ("rejected", "Rejected"),
                            ("accepted", "Accepted"),
                            ("ready_to_dispatch", "Ready to Dispatch"),
                            ("waiting_for_courier", "Waiting for Courier"),
                            ("courier_accepted", "Courier Accepted"),
                            ("picked_up", "Picked Up"),
                            ("delivered", "Delivered"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=255)),
                ("image", models.TextField()),
                ("location", models.CharField(max_length=100)),
                ("rating", models.FloatField(default=3.5)),
                ("distance", models.IntegerField(default=12)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("cafe", "Cafe"),
                            ("asian", "Asian"),
                            ("club", "Club"),
                            ("fast_food", "Fast Food"),
                            ("indian", "Indian"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "menu",
                    models.ManyToManyField(to="restaurant_management_app.menuitem"),
                ),
                (
                    "orders",
                    models.ManyToManyField(to="restaurant_management_app.order"),
                ),
            ],
        ),
    ]
