# Generated by Django 4.2.5 on 2024-05-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("restaurant_management_app", "0001_initial"),
        ("user_management_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_requests",
            field=models.ManyToManyField(to="user_management_app.courier"),
        ),
        migrations.AddField(
            model_name="order",
            name="menu",
            field=models.ManyToManyField(to="restaurant_management_app.menuitem"),
        ),
    ]
