# Generated by Django 4.2.5 on 2024-05-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant_management_app", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem", name="image", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="restaurant", name="image", field=models.TextField(),
        ),
    ]
