# Generated by Django 4.2.5 on 2024-05-20 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user_management_app", "0001_initial"),
        ("restaurant_management_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_requests",
            field=models.ManyToManyField(to="user_management_app.courier"),
        ),
        migrations.AddField(
            model_name="order",
            name="menu",
            field=models.ManyToManyField(to="restaurant_management_app.menuitem"),
        ),
        migrations.AddField(
            model_name="order",
            name="restaurant_instance",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="restaurant_management_app.restaurant",
            ),
        ),
    ]
